// Generated by tools/generate_protocol_contract.py; do not edit.
// Source SHA-256: 6ecdbc7f2694c70c81fdc19d9dfbcd4a805645afa72b8f902c4abcc837e28095
#pragma once

#include <array>
#include <cstddef>
#include <stdexcept>
#include <string>
#include <string_view>

namespace diffexp::kernel::protocol {

enum class ResponseKind { Bounded, ExplicitBulk, Diagnostic };

struct OperationContract {
  std::string_view operation;
  ResponseKind kind;
  std::size_t max_response_bytes;
  bool paged;
};

inline constexpr std::size_t kDiagnosticPageDefault =
    128U;
inline constexpr std::size_t kDiagnosticPageMax =
    256U;

inline constexpr std::array<OperationContract, 71> kOperationContracts{{
    OperationContract{"chart.prepare", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"chart.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"chart.solve", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"chart.solve_batch", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"checkpoint.restore", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"checkpoint.save", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"endpoint.export", ResponseKind::ExplicitBulk, 0U, false},
    OperationContract{"endpoint.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"endpoint.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"integration.export", ResponseKind::ExplicitBulk, 0U, false},
    OperationContract{"integration.line", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"integration.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"integration.run_arms", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"integration.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"local.apply_rational_row", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"local.certify_residual", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"local.endpoint_limit", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"local.evaluate", ResponseKind::ExplicitBulk, 0U, false},
    OperationContract{"local.match", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"local.match_acb", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"local.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"local.release_terminal_factorized_owner", ResponseKind::Bounded, 65536U, false},
    OperationContract{"local.solve", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"local.solve_batch", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"local.specialize_rational_shadow", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"local.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"match.materialize_local", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"match.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"match.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"regular_equation.prepare", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"regular_equation.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"scc.prepare", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"scc.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"scc.solve_column", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"scc.solve_columns", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"scc.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"session.close", ResponseKind::Bounded, 65536U, false},
    OperationContract{"session.counters", ResponseKind::Bounded, 262144U, false},
    OperationContract{"session.create", ResponseKind::Bounded, 65536U, false},
    OperationContract{"session.solve_many", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"session.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"tile.endpoint_limit", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"tile.integration_interval", ResponseKind::Bounded, 65536U, false},
    OperationContract{"tile.match_advance", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"tile.match_interval", ResponseKind::Bounded, 65536U, false},
    OperationContract{"tile.plan", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"tile.plan_arm", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"tile.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"tile.stats", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"transport.consume_hop", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"transport.consume_physical_value_hop", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"transport.consume_value_hop", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"transport.contract", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.contract_pair", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.contract_pair_rolling_stream_add_tile", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"transport.contract_pair_rolling_stream_begin", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"transport.contract_pair_stream_abort", ResponseKind::Bounded, 65536U, false},
    OperationContract{"transport.contract_pair_stream_add_tile", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"transport.contract_pair_stream_begin", ResponseKind::Bounded, 1048576U, false},
    OperationContract{"transport.contract_pair_stream_finish", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.diagnostic_rebuild_terminal_match", ResponseKind::Diagnostic, 8388608U, true},
    OperationContract{"transport.endpoint_batch", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.local_consumer_epsilon", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"transport.publish_consumed_state", ResponseKind::Bounded, 16777216U, false},
    OperationContract{"transport.publish_consumed_states", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.release", ResponseKind::Bounded, 65536U, false},
    OperationContract{"transport.rolling_endpoint_batch", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.run_arm", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.run_arms", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.run_arms_consuming", ResponseKind::Bounded, 67108864U, false},
    OperationContract{"transport.stats", ResponseKind::Diagnostic, 8388608U, true},
}};

constexpr const OperationContract* operation_contract(
    const std::string_view operation) noexcept {
  for (const auto& contract : kOperationContracts)
    if (contract.operation == operation) return &contract;
  return nullptr;
}

inline void enforce_response_budget(const std::string_view operation,
                                    const std::size_t actual_bytes) {
  const auto* contract = operation_contract(operation);
  if (contract == nullptr)
    throw std::logic_error("persistent operation is absent from generated contract: " +
                           std::string(operation));
  if (contract->kind == ResponseKind::ExplicitBulk) return;
  if (actual_bytes > contract->max_response_bytes)
    throw std::length_error(
        "persistent response budget exceeded for " + std::string(operation) +
        ": " + std::to_string(actual_bytes) + " > " +
        std::to_string(contract->max_response_bytes));
}

}  // namespace diffexp::kernel::protocol
