root=ExpandFileName[FileNameJoin[{DirectoryName[$InputFileName],"..",".."}]];
Get[FileNameJoin[{root,"DiffExp.m"}]];base=FileNameJoin[{root,"examples","original"}];
assert[c_,m_]:=If[!TrueQ[c],If[AssociationQ[DiffExp`Private`$lastRequest],Export[FileNameJoin[{root,"build-reference","banana-routes-request.json"}],DiffExp`Private`$lastRequest,"RawJSON"]];Print["FAIL: ",m];Quit[1]];
eq[]:=LoadConfiguration[{MatrixDirectory->FileNameJoin[{base,"Data","Banana","EqualMass"}],EpsilonOrder->4,WorkingPrecision->150,ExpansionOrder->70,DivisionOrder->4,DeltaPrescriptions->{t-16+I δ},UseMobius->True,UsePade->True,Verbosity->1}];
neq[]:=LoadConfiguration[{MatrixDirectory->FileNameJoin[{base,"Data","Banana","UnequalMass"}],EpsilonOrder->4,WorkingPrecision->150,ExpansionOrder->70,DivisionOrder->4,DeltaPrescriptions->{(Sqrt[2]+Sqrt[3/2]+Sqrt[4/3]+1)^2-psq-I δ},UseMobius->True,UsePade->True,Verbosity->1}];
measure[name_,expression_]:=Null;SetAttributes[measure,HoldRest];reports={};
measure[name_,expression_]:=Module[{time,value},{time,value}=AbsoluteTiming[expression];assert[!FailureQ[value],value];AppendTo[reports,<|"phase"->name,"seconds"->time,"native_timings"->DiffExpLastTimings[]|>];Print[name,": ",time," s"];value];
minus=Get[FileNameJoin[{root,"build-reference","banana-wrapper-minus-one.m"}]];
assert[ListQ[minus],"Run original_banana.wl first to derive the asymptotic seed."];
eq[];at32=measure["equal_to_32_saved",TransportTo[minus,{t->x},32,True]];
functions=ToPiecewise[at32];at20=measure["equal_saved_plot_at20",Table[functions[[i,k]][20],{i,4},{k,5}]];
reference20=Get[FileNameJoin[{base,"Reference","BananaEqualMassAt20.m"}]];error20=Max[Abs[at20-reference20]];assert[error20<10^-9,error20];
at2=measure["equal_to_2",TransportTo[minus,{t->2}]];
via2=measure["equal_2_to_32",TransportTo[at2,{t->x},32]];route32error=Max[Abs[via2[[2]]-at32[[1,2]]]];Put[at32,FileNameJoin[{root,"build-reference","banana-wrapper-equal-saved.m"}]];assert[route32error<10^-20,route32error];
lift[equal_,point_]:={point,equal[[2,{1,1,1,1,1,1,2,2,2,2,3,4,4,4,4}]],equal[[3,{1,1,1,1,1,1,2,2,2,2,3,4,4,4,4}]]};
half=measure["equal_to_half",TransportTo[minus,{t->1/2}]];
neq[];b=lift[half,<|psq->1/2,mm1->1,mm2->1,mm3->1,mm4->1|>];
mass=measure["unequal_mass_first",TransportTo[b,<|psq->1/2,mm1->1+x,mm2->1+x/2,mm3->1+x/3,mm4->1|>]];
first=measure["unequal_momentum_to50_saved",TransportTo[mass,<|psq->x,mm1->2,mm2->3/2,mm3->4/3,mm4->1|>,50,True]];
eq[];equal50=measure["equal_momentum_to50",TransportTo[minus,{t->x},50]];
neq[];b=lift[equal50,<|psq->50,mm1->1,mm2->1,mm3->1,mm4->1|>];
second=measure["unequal_mass_at50",TransportTo[b,<|psq->50,mm1->1+x,mm2->1+x/2,mm3->1+x/3,mm4->1|>]];
routeError=Max[Abs[first[[1,2]]-second[[2]]]];assert[routeError<10^-15,routeError];
reference=Get[FileNameJoin[{base,"Reference","BananaUnequalMassAt50.m"}]];
refError=Max[Abs[first[[1,2]]-reference]];assert[refError<10^-9,refError];
report=<|"schema"->"DiffExp.OriginalWrapperValidation/v1","family"->"banana-routes","status"->"passed","equal_reference_at20"->ToString[error20,InputForm],"equal_route_discrepancy_at32"->ToString[route32error,InputForm],"unequal_route_discrepancy_at50"->ToString[routeError,InputForm],"unequal_reference_at50"->ToString[refError,InputForm],"phases"->reports|>;
Export[FileNameJoin[{root,"build-reference","banana-wrapper-routes.json"}],report,"RawJSON"];Print[ExportString[report,"RawJSON"]];Quit[0];
